### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by heiyuxiaokai** [zhangxiaosong18/FreeAnchor#16]
I met this problem with 2080ti. It occurs error after several epoch. Setting image/gpu from 2 to 1 and reducing the gtBoxes of per image didn't work.
Train log:
> out of memory
invalid argument
an illegal memory access was encountered
an illegal memory access was encountered
Traceback (most recent call last):
...
overlaps_th = torch.tensor(overlaps).to(boxlist1.bbox.device) #[N, M]
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::Error'
what(): CUDA error: an illegal memory access was encountered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:569)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fb1e9515813 in /home/fw/Softwares/anaconda3/lib/python3.7/site-packages/torch/lib/libc10.so)

This is my environment information:
> OS: Ubuntu 16.04 LTS 64-bit
Command: conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
GPU: 2080ti
Driver Version: 418.67
Python Version: 3.7
cuda Version: 10.1
cudnn Version: 7
pytorch Version: torch-1.1.0, torchvision-0.2.0

I try to set `CUDA_LAUNCH_BLOCKING` to 1 and meet the same problem. How can I solve it?

**Comment by zhangxiaosong18** [comment]
The first line of the training log you provide is “out of memory”. Is this the reason?

**Comment by heiyuxiaokai** [comment]
Perhaps not. That might be a bug of pytorch. There are some similar problem in pytorch'issues.
