### ISSUE TITLE
训练loss的一些问题

### ISSUE THREAD

**Issue by Z0211** [zhangxiaosong18/FreeAnchor#17]
您好，很感谢您的分享。在读论文的时候关于训练loss有些不太明白，想请教下您：
Loss的部分为什么可以用Mean-max(X)以及FL_(p)替代呢？这里不是很懂，可以说下推导过程么？谢谢您！

**Comment by zhangxiaosong18** [comment]
1.Mean-max是一种选择机制，替换学习目标中的max，在训练的开始更平滑，最终学习目标等价于max。
2.FL(p)这里暂无推导的过程，只是用Focal Loss替换 -log(1 - p)交叉熵损失以解决负样本太多的问题。
欢迎致信 zhangxiaosong18@mails.ucas.ac.cn 进一步讨论！

**Comment by Z0211** [comment]
恩恩，明白了，非常感谢您的回复！谢谢！
