### ISSUE TITLE
Performance gap!

### ISSUE THREAD

**Issue by jiangzhengkai** [zhangxiaosong18/FreeAnchor#19]
Hi, Thanks for your public code. I train this code only get 38.2 mAP on minival datasets. I want to know this is normal fluctuate?

**Comment by zhangxiaosong18** [comment]
The performance on minival set is unstable and I got 38.4-38.7 usually. You can evaluate FreeAnchor on test-dev set.

**Comment by jiangzhengkai** [comment]
@zhangxiaosong18 Thanks
