### ISSUE TITLE
CPU usage goes too high when running demo/webcam.py

### ISSUE THREAD

**Issue by lqzhao** [zhangxiaosong18/FreeAnchor#21]
![image](https://user-images.githubusercontent.com/43566465/70604858-55b4a280-1c34-11ea-9e41-2a65a2266116.png)
it costs too much cpu resources when I run **demo/webcom.py**. It almost occupied all cpus, which makes other program has no cpu resources available. However, it doesn't happen while training or testing. I wonder why it cost so much cpu resource and how can I fix this problem?

I modified the code of **webcom.py** to make a single image as input.

**Comment by 123wk45678** [comment]
do you meet this problem?
ImportError: cannot import name '_C'

**Comment by 123wk45678** [comment]
how to solve it?

**Comment by lqzhao** [comment]
> how to solve it?

You can just force the program to use single thread as follows:
`torch.set_num_threads(1)`
This command can reduce CPU usage effectively with little effect on the speed of inference.

**Comment by lqzhao** [comment]
> ImportError: cannot import name '_C'

Check your environment. Follow the instructions the author provided.

**Comment by yustaub** [comment]
@lqzhao  there are some mistake happened when i run demo on single image, I change the video stream into image in code, and there are some error , can u share your demo code?thank u so much!!

**Comment by lqzhao** [comment]
> @lqzhao there are some mistake happened when i run demo on single image, I change the video stream into image in code, and there are some error , can u share your demo code?thank u so much!!

Leave your email. I'll find that code then send it to you.

**Comment by yustaub** [comment]
@lqzhao  1034397129@qq.com, thank you so much!!!

**Comment by lqzhao** [comment]
> @lqzhao [1034397129@qq.com](mailto:1034397129@qq.com), thank you so much!!!

check it.

**Comment by yustaub** [comment]
> > @lqzhao [1034397129@qq.com](mailto:1034397129@qq.com), thank you so much!!!
> 
> check it.

ok, thanks!
