### ISSUE TITLE
萌新一名，请问必须要搭建maskrcnn-benchmark的环境吗？ I'm a beginner ，do I have to install the environment of maskrcnn-benchmark

### ISSUE THREAD

**Issue by ZSYAD** [zhangxiaosong18/FreeAnchor#22]
本人萌新一个，请问必须要搭建maskrcnn-benchmark的环境才能用freeanchor吗？
 I'm a beginner ，do I have to install the environment of maskrcnn-benchmark

**Comment by zhangxiaosong18** [comment]
你好，请看github第一段，也可以使用mmdetection代码库。

**Comment by ZSYAD** [comment]
好的，多谢
